baseURL = 'https://talesrt.com/'
languageCode = 'en-us'
title = 'talesrt - Character Artist'
theme = 'talesrt'

[params]
  author = "talesrt"
  subtitle = """Lead Character Artist
3D | ZBrush | Blender | Unreal | Unity"""
  description = "Portfolio of talesrt - Lead Character Artist based in Curitiba, Brazil"
  avatar = "/images/avatar.png"
  favicon = "/talesrt_logo.svg"
  heroTagline = "Crafting characters that tell stories"
  cdnUrl = ""  # Add your CDN URL here (e.g., "https://cdn.talesrt.com")
  # Note: Email and social links are centralized in data/contact.yaml
  
  [params.social]
    artstation = "https://artstation.com/talesrt"
    instagram = "https://instagram.com/talesrt"
    twitter = "https://twitter.com/talesrt"
    linkedin = "https://linkedin.com/in/talesrt"
    youtube = "https://youtube.com/@talesrt"
    # Note: Email is centralized in data/contact.yaml

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false  # Set to true only if you need to embed custom HTML in markdown files
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true

[ignoreLogs]
  error = []
  warning = ["warning-goldmark-raw-html"]

[taxonomies]
  tag = "tags"
  category = "categories"
